### ISSUE TITLE
[Typo]: Familiar Ability Prerequisite Links

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#12]
### What happened?

Assimilate II has a link to Assimilate I in its Prerequisite description, something Armour Thief II, Assimilate III, Growth II and Growth III lack.

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/ef192a67-b7bd-4f92-817b-87822791e92c)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/957e221e-7de0-48a7-8b37-f2319d8306ea)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/9c19a01b-97ee-46a7-888b-8ce627782dcf)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/d23a3207-2b2f-461b-ba46-12756efd7701)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/f29850bf-b8ce-4ccb-835b-bdb3895e5e40)

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Decided to not link in pre-req, removed linking to stay consistent.
