### ISSUE TITLE
[Typo]: Heartbeater old version

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#13]
### What happened?

The Heartbeater item was changed at some point and the version on Foundry VTT isn't up to date - The Hollow Beat feature was changed from the Toll the Dead cantrip to the Chill Touch cantrip. The description was also updated to match the new spell, and so were the rarity variants. Additionally, the Uncommon variant of the item doesn't have the Hollow Beat property, nor does it have any charges.

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/1433e870-321b-4926-a078-bea8b2b5d7ff)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/899e78a1-a5c5-4f41-9c13-0887e061eab3)

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by MrVauxs** [comment]
Also an issue in The Failed Gods item pack.

**Comment by Bob-the-Tree** [comment]
Updated in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
