### ISSUE TITLE
[Typo] Maiden's Tower very rare save DC

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#14]
### What happened?

The very rare variant of the Maiden's Tower increases the save DC for Locked In from 15 to 16, which is missing from the VTT version

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/a92c37ed-fe15-4fa0-8b2d-fc518d63498d)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/c390572f-713d-4c09-be24-0dc0d0234b7c)

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Updated in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
