### ISSUE TITLE
[Missing]: Rosey Knightscream

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#15]
### What happened?

The Rosey Knightscream, a Magical Meal made from the Amalgamooze, is nowhere to be found in the module. Should be in items

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Magical meals only referenced in the MotD distro PDF, not individual hunt PDFs. Narb is looking into adding magical meals to the compilation module rather than each hunt module.

**Comment by MrVauxs** [comment]
Fixed in 0.9.2.
