### ISSUE TITLE
[Typo]: Clue 3 not Transparent

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#16]
### What happened?

The Clue 3 isn't transparent like the rest of them, I'll send the correct one in the discord

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by MrVauxs** [comment]
For @Bob-the-Tree, the Clue image: https://discord.com/channels/884811551062753301/1113934419720413184/1195428234171535371
