### ISSUE TITLE
[Typo]: Legendary Action Bar inconscistency

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#17]
### What happened?

The Ooze Dragons all have an additional bar in their token to keep track of Legendary Actions, which is great! The issue is, the Ooze Knight, whom also has legendary actions, does not have an additional bar of its own. I think commiting to either having a bar or not could be better

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/2446b076-69ee-4228-83ef-be3e20c5391c)

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Removed the legendary action bar for consistency with other modules.
