### ISSUE TITLE
[Typos]: Missing Light Spheres

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#20]
### What happened?

During Wave 1 of the fight, the Pontiff is immune to damage and players have the option to destroy four light spheres spread across the cathedral to make the Pontiff vulnerable to damage again. These light spheres are marked by an S on the map of the Lower Cathedral Floor, and each have their own AC and HP, as well as damage immunities - these could be their own tokens so players can target them

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/82bd28b9-6981-41d2-ac2e-59ac0d28d304)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/6f327ebc-5ec9-499f-ace1-c52bedbc0501)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Added tokens to each level's wave with AC and HP reflected.
