### ISSUE TITLE
[Missing]: Candlelight Fondue item missing

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#33]
### What happened?

Candlelight Fondue, a magical meal made from the Pontiff's component, is missing from the module

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/dee1c482-5842-45bb-bffe-80d1ad432aac)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by MrVauxs** [comment]
Fixed in 0.9.2.
