### ISSUE TITLE
[Typo]: Candlebrand Ring charges

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#34]
### What happened?

The rare and uncommon versions should have 3 charges, not 5

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/87990e9c-cb52-4c11-a33e-8e15e7b82bc8)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Fixed in module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
