### ISSUE TITLE
[Typo]: Candlebrand Ring spell link

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#35]
### What happened?

_Shield of Faith_ should be linked similar to the _Magic Circle_ spell in the example below

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/e058a40c-6c27-4f30-892d-a93155991bc4)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/ad35a709-398a-425d-9b03-97ffc479784c)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Updated in individual module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
