### ISSUE TITLE
[Typo]: Maiden's Tower banishment spell

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#36]
### What happened?

Maiden's Tower _Banishment_ spell should be linked to the SRD spell like in the example below

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/2d769da0-9a62-42bc-8e24-cd2ac3b2b0f5)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/505625ce-23d1-4d5b-9155-a4bbe2a932c7)

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Updated in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
