### ISSUE TITLE
[Typo]: Candlebrand Ring, Uncommon issues

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#37]
### What happened?

This ONLY APPLIES to the UNCOMMON variant of the ring

- As stated in a previous typo report, charges should be 3, not 5;
- "...spell for 10 minutes, or until you lose concentration."
- DC should be lowered to 13
- to hit bonus should be lowered to +5

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/3c634394-4687-45b1-8215-739a28a566c1)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/6c1e05d6-c59d-4c18-9d72-e0c360206e7f)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/0b4e9f41-a4bb-4395-ab5a-c3f185010192)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/4f13ab7d-1fb8-4af5-943e-6a683b42b211)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Update in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
