### ISSUE TITLE
[Typo]: Candlebrand Ring, Very Rare issues

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#38]
### What happened?

This only applies to the VERY RARE variant of them item:
- to hit bonus should be raised to +8
- save DC should be raised to 16

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/29491b33-a8b2-45f6-8ec4-ec64dc7ccadd)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/48d4f30b-2ece-46bc-8626-558da6ef625a)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Updated in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
