### ISSUE TITLE
[Typo]: Candlelight Mitre, Uncommon - wrong feature

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#39]
### What happened?

The Uncommon variant of them item requires two charges to use the _Burn the Lies_ trait, not Cleanse the Sins! Cleanse the Sins should cost one charge and Burn the Lies should cost two.

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/f9e29ebe-7806-4715-baaa-26504f51e3be)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/752a722d-2dd4-4a24-87f1-3f4c49d43db4)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Updated in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
