### ISSUE TITLE
[Typo]: Waxen Sceptre spell links

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#40]
### What happened?

All of the links for the spells in the Wax On property are broken

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/e9f1bf36-874b-4653-aced-3d0cc6e16ff1)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Resolved in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
