### ISSUE TITLE
[Typo]: Waxen Sceptre, Very Rare spell

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#41]
### What happened?

As well as the Wax On spells, the Living Candle spell link is broken

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/8cfd8a0f-9f45-456a-9f76-5da4a5110436)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Resolved in hunt module.

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.
