### ISSUE TITLE
[Typo]: Flames of the Faithful Magic Items formatting

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#42]
### What happened?

Outside of Arcanowax, all items in Flames of the Faithful are missing proper formatting (bolding and italics)

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/80ec9557-917b-4785-90da-d3295cb8137a)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/644d4a1c-e3dc-4cdf-8065-9165f92d3b2a)

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by MrVauxs** [comment]
Fixed in The Failed Gods.

**Comment by Bob-the-Tree** [comment]
Resolved in adventure module.
