### ISSUE TITLE
[Typo]: Corrupted Megaconstruct vision

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#50]
### What happened?

Corrupted Megaconstructs (CR 3, use Knight as a base) have no vision attached to them

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/b860f6b7-3545-46af-a9b3-343816b52697)

### What package are you reporting this for?

Forge of the Divine Machine

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
No vision changes were mentioned in the modifications, and Knight has no special vision by default. Added 120 ft basic vision per Narb.
