### ISSUE TITLE
[Typo]: Mecharmadillo Clingy trait 

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#55]
### What happened?

Clingy should be a feature, not action

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/deaebb96-22e0-4b08-99fc-0c183566b56b)

### What package are you reporting this for?

Forge of the Divine Machine

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Clingy is classified as a feature, but Foundry moves anything that uses any of the fields used in "Feature Usage" to actions (basically when Activation Cost is not blank). It is a strange bug when a feature is not a "passive" feature.
