### ISSUE TITLE
[Missing]: Holo-roast Supplement

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#59]
### What happened?

The magical meal Holo-roast Supplement, made from components from the Unit M3t4l, is nowhere to be seen

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/964b4f54-9b42-42ef-842f-070669f84a29)

### What package are you reporting this for?

Forge of the Divine Machine

### Version

0.9.1

**Comment by MrVauxs** [comment]
Fixed in 0.9.2.
