### ISSUE TITLE
[Typo]: Railbow, Very Rare Cover Blower

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#60]
### What happened?

1d6 at the bottom should be 1d8

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/5865b2cf-d054-4d65-bcc6-6a7a27aa0f7a)

### What package are you reporting this for?

Forge of the Divine Machine

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Fixed in module.

**Comment by MrVauxs** [comment]
Fixed in pack.
