### ISSUE TITLE
[Typo] Tableturner, Common attunement

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#61]
### What happened?

The Common variant of the Tableturner doesn't require attunement. Additionally, they all are formatted weirdly - feature names should be bold and italics in the same line as the feature

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/911aafc4-7a3a-4597-afe6-bfcf74da7041)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/af860673-6074-440b-ad54-219379d15542)

### What package are you reporting this for?

Forge of the Divine Machine

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Fixed in module.

**Comment by MrVauxs** [comment]
Fixed in pack.
