### ISSUE TITLE
[Typo] Forge of the Divine Machine formatting

### ISSUE THREAD

**Issue by eldritchwhispers** [Loot-Foundry/loot-tavern-content#62]
### What happened?

Most if not all of the items in FotDM are missing proper formatting like bolding and italics, especially when it comes to bolding the number of charges and how many are recharged daily

![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/b43e2103-ef8c-49b5-b32b-3500ee49ef04)
![image](https://github.com/Loot-Foundry/loot-tavern-content/assets/156443610/204ea6de-cc89-4338-925c-1677474b7a87)

### What package are you reporting this for?

Forge of the Divine Machine

### Version

0.9.1

**Comment by MrVauxs** [comment]
Fixed in pack.

**Comment by Bob-the-Tree** [comment]
Fixed in adventure module.
