### ISSUE TITLE
Bones'n'Roses - Foundry Module Review

### ISSUE THREAD

**Issue by HarrisonMAD** [Loot-Foundry/loot-tavern-content#63]
### Scene

- No Issues, although there are  no lighting effects on the scene and a couple of places that could benefit from this (water, the coin on the forehead)

### Actors

- Actors are not grouped into level 5/15/18 range folders, and the level range isn’t in their actor name either, so the folder is just one big dump of unorganised actors.
- Black Puddling - Vision Enabled not ticked
- Adult Ooze Dragon - Forgotten Adventures Artwork note in biography tab.
- Ancient Ooze Dragon - Forgotten Adventures Artwork note in biography tab.
- Decahedrooze - Vision is set to have tremorsense but senses panel in attributes only has blindsight.
- Ghoul - Forgotten Adventures Artwork note in biography tab.
- Hexahedrooze - Vision is set to have tremorsense but senses panel in attributes only has blindsight.
- Minotaur Skeleton -  Forgotten Adventures Artwork note in biography tab.
- Minotaur Skeleton - Vision Enabled not ticked
- Octahedrooze - Vision is set to have tremorsense but senses panel in attributes only has blindsight.
- Ooze Dragon Wyrmling - Forgotten Adventures Artwork note in biography tab.
- Ooze Knight - Vision distances were set in but units not selected, so showed as 120 null (needs feet selecting)
- Ooze Knight Champion - Vision distances were set in but units not selected, so showed as 120 null (needs feet selecting)
- Ooze Knight Warlord - Vision distances were set in but units not selected, so showed as 120 null (needs feet selecting)
- Ooze Remnant Animated Armor - Forgotten Adventures Artwork note in biography tab.
- Ooze Remnant Assassin - Forgotten Adventures Artwork note in biography tab.
- Ooze Remnant Gladiator - Forgotten Adventures Artwork note in biography tab.
- Ooze Remnant Knight - Forgotten Adventures Artwork note in biography tab.
- Ooze Remnant Roper - Forgotten Adventures Artwork note in biography tab.
- Ooze Remnant Stone Golem - Forgotten Adventures Artwork note in biography tab.
- Note: All Ooze Remnant Actor abilities still retain the name of the pre-ooze creature.
- Skeleton - Forgotten Adventures Artwork note in biography tab.
- Wight - Forgotten Adventures Artwork note in biography tab.
- Young Ooze Dragon - Forgotten Adventures Artwork note in biography tab.

### Items

- Ooze Dragon Bone - grammar error, should be harvested from AN ooze, says a ooze.
- Note: All actors and abilities have a source of MotD. Items all have Loot Tavern. Intended?
- Heartbeater (all versions) - broken spell link to toll the dead in the Hollow Beat feature.
- Liberator Weapons - The extra radiant damage reads as only being the first time you hit a creature each turn, but the radiant damage is built into the regular damage of the sword. This means a lot of manually correcting for the DM and will be irritating. Suggest making it an optional application button.

### What package are you reporting this for?

Bones n' Roses

### Version

0.9.1

**Comment by MrVauxs** [comment]
The Liberator swords (from _The Blademasters Trove_) have been updated to have the additional damage be in the extra Roll Formula, rather than the actual damage roll. Up to Bob now to copy the items.

Heartbeater has been fixed in an update to _The Failed Gods_ item pack. Same as above.

The sources being all different are because of the fact they are copied from the aforementioned item packs. Up to Bob to decide if they want to mass-edit the items to match. This also applies to this question being raised in issue #64.

**Comment by Bob-the-Tree** [comment]
Resolved.
