### ISSUE TITLE
Flames of the Faithful - Foundry Module Review

### ISSUE THREAD

**Issue by HarrisonMAD** [Loot-Foundry/loot-tavern-content#64]
### Scene

- No Issues, although there are  no lighting effects on the scene and a couple of places that could benefit from this (stained glass windows, candelabras)

### Actors

- Actors are not grouped into level 5/15/18 range folders, and the level range isn’t in their actor name either, so the folder is just one big dump of unorganised actors.
- Waxolotl - I can no longer function. This guy is too cute.
- Note: All of the Pontiff and Wax Elemental enemies have their token art as their character art, unlike Bones’n’Roses. I can see in the module folder that there is intended creature artwork for these actors.
- Wax Elemental Animated Armor - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Black Pudding - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Gargoyle - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Gray Ooze - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Knight - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Magma Mephit - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Shambling Mound - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Shield Guardian - Forgotten Adventures Artwork note in biography tab.
- Wax Elemental Stone Golem - Forgotten Adventures Artwork note in biography tab.
- Note: All Wax Elemental Actor abilities still retain the name of the pre-wax creature.

### Items

- The component items all have the grammatical error “harvested from a elemental” instead of “an elemental”.
- Magical Items have the source “FBI” which if not Loot Tavern also doesn’t make sense for the adventure name?
- Some magical items have the source Loot Tavern
- Waxen Sceptre - Spell links for the coloured candles are all broken

### What package are you reporting this for?

Flames of the Faithful

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Resolved.
