### ISSUE TITLE
Forge of the Divine Machine - Foundry Module Review

### ISSUE THREAD

**Issue by HarrisonMAD** [Loot-Foundry/loot-tavern-content#65]
### Scenes

- Very cool, no issues, good use of lighting effects.

### Actors

- Actors are not grouped into level 5/15/18 range folders, and the level range isn’t in their actor name either, so the folder is just one big dump of unorganised actors.
- Corrupted Exaconstruct - Forgotten Adventures Artwork note in biography tab.
- Corrupted Gigaconstruct - Forgotten Adventures Artwork note in biography tab.
- Corrupted Kiloconstruct - Forgotten Adventures Artwork note in biography tab.
- Corrupted Megaconstruct - Forgotten Adventures Artwork note in biography tab.
- Corrupted Petaconstruct - Forgotten Adventures Artwork note in biography tab.
- Corrupted Teraconstruct - Forgotten Adventures Artwork note in biography tab.
- Minion Construct Animated Armor - Forgotten Adventures Artwork note in biography tab.
- Minion Construct Half-Red Dragon Veteran - Forgotten Adventures Artwork note in biography tab.
- Minion Construct Knight - Forgotten Adventures Artwork note in biography tab.
- Note: All Corrupted construct abilities reference their pre-construct creatures

### Items

- Familiar Features - The Mecharmadillio features do not have (Mecharmadillo) in the item name, unlike the Black Puddling and Waxolotl ability items in the other adventures.
- Caster Blaster (Rare) - Still set to Uncommon in Rarity
- Tableturner - Item features are not bold italicised like in every other item.

### What package are you reporting this for?

Forge of the Divine Machine

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Resolved.
