### ISSUE TITLE
The Twilight Hunter - Foundry Module Review

### ISSUE THREAD

**Issue by HarrisonMAD** [Loot-Foundry/loot-tavern-content#66]
### Scene

- No Issues, although there are  no lighting effects on the scene and a couple of places that could benefit from this (rivers, firefly pockets)

### Actors

- Actors are not grouped into level 5/15/18 range folders, and the level range isn’t in their actor name either, so the folder is just one big dump of unorganised actors.
- Blood Wolf - Forgotten Adventures Artwork note in biography tab.
- Sanguine Bloodhound - has an entirely separate actor just to reflect being in mythic state, even though both actors have the mythic trait feature (only difference seems to be the flight speed)
- Dire Wolf - Forgotten Adventures Artwork note in biography tab.
- Poison Wolf - Forgotten Adventures Artwork note in biography tab.
- Swarm of Dire Ravens - Forgotten Adventures Artwork note in biography tab.
- Swarm of Ravens - Forgotten Adventures Artwork note in biography tab.
- Wolf - Forgotten Adventures Artwork note in biography tab.

### Items

- Bloodhound’s Immobiliser (Uncommon) has been created as a loot type item, not a useable weapon. Therefore it has no Foundry functionality.
- Bloodhound’s Immobiliser (Rare) has been created as a loot type item, not a useable weapon. Therefore it has no Foundry functionality.

### What package are you reporting this for?

The Twilight Hunter

### Version

0.9.1

**Comment by Bob-the-Tree** [comment]
Resolved.
