### ISSUE TITLE
Throne of the Devourer - Foundry Module Review

### ISSUE THREAD

**Issue by HarrisonMAD** [Loot-Foundry/loot-tavern-content#67]
### Scene

- Does it make sense to have the Friesian Horses be invisible walls instead of terrain walls? They’re meant to provide cover and be difficult to bypass, after all.
- Massive missed opportunities with the total lack of scene lighting. Dark map with a lot of lit torches - this could look much better for 1 minute’s effort.

### Actors

- Actors are not grouped into level 5/15/18 range folders, and the level range isn’t in their actor name either, so the folder is just one big dump of unorganised actors.
- Celestial Devourer Magnus - Vision distances were set in but units not selected, so showed as 120 null (needs feet selecting)
- Celestial Devourer Medius - Vision distances were set in but units not selected, so showed as 120 null (needs feet selecting)
- Celestial Devourer Parvus - Vision distances were set in but units not selected, so showed as 120 null (needs feet selecting)
- Corrupted Brute - Abilities reference Gladiator
- Corrupted Brute - Forgotten Adventures Artwork note in biography tab.
- Corrupted Executioner - Abilities reference Chain Devil
- Corrupted Executioner - Forgotten Adventures Artwork note in biography tab.
- Corrupted Knight - Forgotten Adventures Artwork note in biography tab.
- Corrupted Priest - Forgotten Adventures Artwork note in biography tab.
- Corrupted Warrior - Abilities reference Animated Armor
- Corrupted Warrior - Forgotten Adventures Artwork note in biography tab.
- Dustwretches - Abilities reference Dust Mephit
- Dustwretches - Forgotten Adventures Artwork note in biography tab.
- Flesh Golem - Forgotten Adventures Artwork note in biography tab.
- Gameela Haddad - Abilities reference priest
- Gameela Haddad - Forgotten Adventures Artwork note in biography tab.
- Glabezru - Forgotten Adventures Artwork note in biography tab.
- Hell Hound - Forgotten Adventures Artwork note in biography tab.
- Hezrou - Forgotten Adventures Artwork note in biography tab.
- Pegasus - Forgotten Adventures Artwork note in biography tab.
- Shield Guardian - Forgotten Adventures Artwork note in biography tab.
- Stone Golem - Forgotten Adventures Artwork note in biography tab.
- Vrock - Forgotten Adventures Artwork note in biography tab.

### Items

- Familiar Features - The Handipede features do not have (Handipede) in the item name, unlike the Black Puddling and Waxolotl ability items in the other adventures
- Clutching Crown - Broken Spell link to chill touch in Touch of the Grave feature
- Grasping Mantle - Broken spell link to Mage Armor in Helping Hands trait

### What package are you reporting this for?

Throne of the Devourer

### Version

0.9.1

**Comment by MrVauxs** [comment]
Clutching Crown and Grasping Mantle have been fixed in _The Failed Gods_ item pack, up to Bob to copy paste from the source.

**Comment by Bob-the-Tree** [comment]
Resolved.
