### ISSUE TITLE
Good, The Bad, the Oni - Foundry Module Review

### ISSUE THREAD

**Issue by HarrisonMAD** [Loot-Foundry/loot-tavern-content#69]
### What kind of problem are you facing?

Missing Content (entire statblocks are missing)

### Module
- The Scene, Actor, and Item folders for 'The Good, the Bad, the Oni' all have different category colours assigned.
### Scene
- There is a 5ft square spell template left on the map by default, visible to players. Presume this is a misclick from when the map was being walled, but if not (for example, a trap) it should be noted more visibly.
- Some of the environment uses terrain walls in a way that makes no sense (north entrance) overlaid on top of invisible walls?
### Actors
- Monster ability texts have a variety of different formatting. Presumably some are typed from scratch and others are copy/pasted from other sources?
- Monsters don't have any source
- Shr-Imp still has default FA token art, Imp name in abilities.
- Durian Devil still has default FA token art and Barbed Devil in item descriptions
- Vulchurro still has default FA token art and Vrock in item descriptions
### Items
- All items have broken thumbnails, item art is linking to a broken directory
- All items have 'Cakewalk' as their source. Presume all the art thumbnails are pointing to a different cakewalk module directory?

### What package are you reporting this for?

Other?

### Version

1.2.0

**Comment by MrVauxs** [comment]
Resolved.
